package p455w0rdslib;

import java.util.Arrays;
import java.util.concurrent.*;

import net.minecraftforge.fml.common.ModMetadata;

public class LibGlobals {
	public static final String MODID = "p455w0rdslib";
	public static final String VERSION = "2.1.44";
	public static final String NAME = "p455w0rd's Library";
	public static final String SERVER_PROXY = "p455w0rdslib.proxy.CommonProxy";
	public static final String CLIENT_PROXY = "p455w0rdslib.proxy.ClientProxy";
	public static final String DEPENDENCIES = "after:redstoneflux;after:mantle;after:tconstruct;after:enderio;after:projecte;after:tesla";
	public static final String CONFIG_FILE = "config/p455w0rdsLib.cfg";
	public static final ExecutorService THREAD_POOL = new ThreadPoolExecutor(0, 2, 1, TimeUnit.MINUTES, new LinkedBlockingQueue<Runnable>());
	public static int ELAPSED_TICKS = 0;
	public static int RED = 255;
	public static int GREEN = 0;
	public static int BLUE = 0;
	public static int TURN = 0;
	public static float TIME = 0.0F;
	public static float TIME2 = 0.0F;
	public static boolean IS_CONTRIBUTOR = false;
	public static boolean CONTRIBUTOR_FILE_DOWNLOADED = false;

	public static class ModInfo {

		public static void setData() {
			final ModMetadata meta = new ModMetadata();
			meta.autogenerated = false;
			meta.modId = MODID;
			meta.name = NAME;
			meta.version = VERSION;
			meta.credits = "TheRealp455w0rd";
			meta.authorList = Arrays.asList(new String[] {
					"TheRealp455w0rd"
			});
			meta.description = "Library component for all of p455w0rds mods";
			meta.url = "http://p455w0rd.net/";
			P455w0rdsLib.meta = meta;
		}

	}

	public static class ConfigOptions {

		public static boolean ENABLE_CONTRIB_CAPE = true;
		public static boolean ENABLE_CONTRIB_PARTICLES_SELF = true;
		public static boolean ENABLE_CONTRIB_PARTICLES_OTHERS = true;

	}
}
